name: tale-stories
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asgiref=3.7.2
  - backports.zoneinfo=0.2.1
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - django=4.2.1
  - djangorestframework=3.14.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libpq=15.3
  - libsqlite=3.42.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.1
  - pip=23.1.2
  - psycopg=3.1.9
  - psycopg-c=3.1.9
  - python=3.10.11
  - python_abi=3.10
  - pytz=2023.3
  - readline=8.2
  - setuptools=67.7.2
  - sqlparse=0.4.4
  - tk=8.6.12
  - typing_extensions=4.6.2
  - tzdata=2023c
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - django-extensions==3.2.1
      - djangorestframework-simplejwt==5.2.2
      - drf-spectacular==0.26.2
      - idna==3.4
      - inflection==0.5.1
      - pyjwt==2.7.0
      - pyyaml==6.0
      - six==1.16.0
      - typing-extensions==4.5.0
      - uritemplate==4.1.1
